// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dsudtuabcjhjbzlsdzza.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzdWR0dWFiY2poamJ6bHNkenphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAxOTQyNzQsImV4cCI6MjA4NTc3MDI3NH0.Fkng64PpLSip60Pyzv7kHVRlMVCxXTFDP-zNrgE0JCs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});